name: CD

on:
  workflow_dispatch:
  push:
    branches:
      - main

# Allow only 1 CD workflow at a time
concurrency:
  group: cd
  cancel-in-progress: false

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest

    env:
      node-version: '18.x'
      RELEASE_VERSION: v0.1.${{github.run_number}}

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ env.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.node-version }}

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Build app
      run: npm run build --prod

    - name: Zip build result
      run: |
        cd dist/haddy-sim-hub-client
        zip -r haddy-simhub-client *

    - name: Create release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.RELEASE_VERSION }}
        release_name: Release ${{ env.RELEASE_VERSION }}
        draft: true
        prerelease: false

    - name: Upload release assets
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/haddy-sim-hub-client/haddy-simhub-client.zip
        asset_name: haddy-simhub-client.zip
        asset_content_type: application/zip

    - name: Publish Release
      uses: eregon/publish-release@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        release_id: ${{steps.create_release.outputs.id}}

